### ISSUE TITLE
Axis Label string formatter

### ISSUE THREAD

**Issue by tonka3000** [gtktsc/ascii-chart#1]
Hi @gtktsc ,

Great library. I would have a feature request. I would need to format the label differently. I have bigger number (mostly y-axis) which are between 0 - 1000000. The actual formatter can only return a number again (so divide the number is the way is use it, but it is confusion to read). It would be great to have a string based formatter that I can translate i.e. 10000 to 10K as label. Directly built in would also be fine.

Greetings
Michael

**Comment by gtktsc** [comment]
Hey @tonka3000! Thank you very much and thanks for raising this issue, good idea! I've included this functionality in a new formatter in [the latest version](https://github.com/gtktsc/ascii-chart/commit/e23f41b5750d7e33724a2e0c1f8abcb2f672b057). Is this what you need?

**Comment by gtktsc** [comment]
Hey!

It's because I've disabled new formatting for small numbers:
```
defaultFormatter = (value, { xRange, yRange }) => {
  // Cut off small values
  if (Math.abs(xRange[0]) < 1000 || Math.abs(yRange[0]) < 1000) {
    return Number(value.toFixed(3));
  }
  // Adds XYZk to cut off large values
  if (Math.abs(value) > 1000) return `${value / 1000}k`;
  return value;
};
```
To make it work try this:
```
const coords: Coordinates = [
  [ 0, 6000 ],      [ 100, 9000 ],
  [ 200, 9100 ],   [ 300, 9200 ],
  [ 400, 9344 ],   [ 500, 9877 ],
  [ 600, 10200 ],  [ 700, 15000 ],
  [ 800, 9100 ],   [ 900, 9200 ],
  [ 1000, 9344 ],  [ 1100, 9877 ],
  [ 1200, 10001 ], [ 1300, 9000 ],
  [ 1400, 9100 ],  [ 1500, 9200 ],
  [ 1600, 9344 ],  [ 1700, 9877 ],
  [ 1800, 10001 ], [ 1900, 9000 ],
  [ 2000, 9100 ],  [ 2100, 9200 ],
  [ 2200, 9344 ],  [ 2300, 9877 ],
  [ 2400, 10001 ], [ 2500, 10001 ],
  [ 2600, 9000 ],  [ 2700, 9100 ],
  [ 2800, 9200 ],  [ 2900, 9344 ],
  [ 3000, 9877 ],  [ 3100, 10001 ]
];

const chart = plot(coords, { "height": 12, width: 60, "hideXAxis": true, "formatter": (value) => {
  if (Math.abs(value) > 1000) return `${value / 1000}k`;
  return value;
},});


```

**Comment by gtktsc** [comment]
Hello @tonka3000

Yes, that's because I've added additional transformation for small numbers, but apparently it wasn't good enough. It's gone now, please try out the newest release. 

Thanks!

**Comment by tonka3000** [comment]
@gtktsc Works perfect. Thank you very much.
