### ISSUE TITLE
simply importing library outputs a default chart. 

### ISSUE THREAD

**Issue by electic** [gtktsc/ascii-chart#3]

**Comment by electic** [comment]
![Screen Shot 2022-07-23 at 7 10 38 PM](https://user-images.githubusercontent.com/43028/180625713-a55ebeb1-66d6-41e1-9dce-f0303290c670.png)

**Comment by gtktsc** [comment]
Hello @electic, I'm really sorry for the response time. I was not notified about your comment. Your PR was merged in, a new version was deployed - as you said - it should fix the problem. Sorry for your inconvenience.

**Comment by electic** [comment]
> Hello @electic, thank you very much for your kind words and help! I'm really sorry for the response time. I was not notified about your comment. Your PR was merged in, a new version was deployed - as you said - it should fix the problem. Sorry for your inconvenience.

Not at all. I am really happy you made this. Really cool, appreciate the merge.
