### ISSUE TITLE
More customization

### ISSUE THREAD

**Issue by kaushals-mecha** [gtktsc/ascii-chart#4]
Hey, This is the best terminal ascii chart!

I had a small issues/question.
Current Output
![hii](https://github.com/gtktsc/ascii-chart/assets/123261508/f0de2cff-46b9-4daa-806c-761a7e27844c)

I wanted something like this, not exact but few things like
![hiu](https://github.com/gtktsc/ascii-chart/assets/123261508/1f5db0f0-efc3-494e-9b69-6cc2828ee4ab)

1. Empty symbol only between/inside the graph
2. The right corner mentions the types that graph lines belong to (Yesterday, today)
3. The way to add label to x and y axis in the chart, currently we can only add title.

Great library! I can't wait to see where this goes. Thank you for making it!

**Comment by gtktsc** [comment]
Hey @kaushals-mecha, thanks for raising this issue!

1. What do you mean by empty symbol only between/inside the graph? To not render the "-" symbols outside the axis? To make it looks like 
```
------------->
1 2 3 4 5 6 7 
```
instead of:
```
------------->
1-2-3-4-5-6-7 
```
Sounds like a good idea, I'll take a look at it

2. Good idea :👍 , I'll try to implement legends. 
3. Not sure if I understand correctly. Label like "%" or "pm"? There is a way to do custom formatter for lines:
```
  plot(
    [
      [
        [0, -10],
        [1, 0.001],
        [2, 10],
        [3, 200],
        [4, 10000],
        [5, 2000000],
        [6, 50000000],
      ],
    ],
    {
      width: 30,
      height: 20,
      formatter: (n: number, { axis }: FormatterHelpers) => {
        const labels = ['A', 'B', 'C', 'D', 'E', 'F', 'G'];
        if (axis === 'y') return n;
        return labels[n] || 'X';
      },
    },
  )

         ▲
 50000000┤                            ┏━
         │                            ┃
         │                            ┃
         │                            ┃
         │                            ┃
         │                            ┃
         │                            ┃
         │                            ┃
         │                            ┃
         │                            ┃
         │                            ┃
         │                            ┃
         │                            ┃
         │                            ┃
         │                            ┃
         │                            ┃
         │                            ┃
         │                            ┃
  2000000┤                       ┏━━━━┛
      -10┤━━━━━━━━━━━━━━━━━━━━━━━┛
         └┬────┬────┬────┬───┬────┬────┬▶
          A    B    C    D   E    F    G

```

If you'd like to add "%" or "pm" you might want to do something like:
```
 formatter: (n: number, { axis }: FormatterHelpers) => {
        const labels = ['A', 'B', 'C', 'D', 'E', 'F', 'G'];
        if (axis === 'y') return `${n}%`;
        return `${n}pm`;
      },
```

I'll take a look at it and will get back to you later! Thanks!

**Comment by gtktsc** [comment]
I've added a few new options:
```
legend?: { position?: 'left' | 'right' | 'top' | 'bottom'; series: string | string[] };
xLabel?: string;
yLabel?: string;
```

and new symbols: 
```
background?: string;
border?: string;
```

Here is an example:
```
plot(
 [
      [
        [1, 1],
        [2, 2],
        [3, 4],
        [4, 6],
      ],
      [
        [5, 4],
        [6, 1],
        [7, 2],
        [8, 3],
      ],
    ],
    {
      width: 20,
      fillArea: true,
      color: ['ansiGreen', 'ansiBlue'],
      legend: { position: 'bottom', series: ['first', 'second'] },
    },
);

 ▲
6┤       ██
 │       ██
4┤    █████  ███
3┤    █████  ███    ██
2┤  ███████  ███ █████
1┤█████████  █████████
 └┬──┬─┬──┬──┬──┬─┬──┬▶
  1  2 3  4  5  6 7  8
█ first
█ second

```
It should cover your needs. Please let me know if you need something else. I'm closing this issue for now. Thanks again!

**Comment by kaushals-mecha** [comment]
Thanks a lot for quick solutions! really appreciated!

**Comment by kaushals-mecha** [comment]
My third point was to add 

The way to add label to x and y axis in the chart, currently we can only add title.
as you can see x-asis is labelled as `usage` in the image i shared,

**Comment by gtktsc** [comment]
Hey @kaushals-mecha, in the latest version I've also added `xLabel` and `yLabel` options, used as:
```
plot(
  [
    [1, 1],
    [2, 4],
    [3, 4],
    [4, 2],
    [5, -1],
    [6, 3],
    [7, -1],
    [8, 9],
  ],
  { xLabel: 'x', yLabel:'y', width: 20, height: 8 },
);

   ▲
  9┤                  ┏━
   │                  ┃
   │                  ┃
  4┤  ┏━━━━┓          ┃
  3┤  ┃    ┃     ┏━┓  ┃
y 2┤  ┃    ┗━━┓  ┃ ┃  ┃
  1┤━━┛       ┃  ┃ ┃  ┃
 -1┤          ┗━━┛ ┗━━┛
   └┬──┬─┬──┬──┬──┬─┬──┬▶
    1  2 3  4  5  6 7  8
             x
             
```
Is this what you need?

**Comment by kaushals-mecha** [comment]
Also is there any way is we could give the width in percentages as in `"50%", "100%"`

i am really sorry for demanding lot of customizations

**Comment by kaushals-mecha** [comment]
Okay got it, not an issue thanks for the clarification
